services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel-offer-app
    environment:
      PORT: 8000
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_NAMESPACE: default
      TEMPORAL_TASK_QUEUE: hotel-offers-task-queue
      REDIS_URL: redis://redis:6379
    ports:
      - "8000:8000"
    depends_on:
      - temporal
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel-offer-worker
    command: npm run start:worker
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_NAMESPACE: default
      TEMPORAL_TASK_QUEUE: hotel-offers-task-queue
      SUPPLIER_BASE_URL: http://app:8000
    depends_on:
      - temporal
      - app

  temporal:
    image: temporalio/auto-setup:latest
    container_name: hotel-offer-temporal
    ports:
      - "7233:7233"

  redis:
    image: redis:7-alpine
    container_name: hotel-offer-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
